version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  install-pnpm:
    steps:
      - run:
          name: install pnpm
          command: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7

jobs:
  install-deps:
    executor: node/default
    steps:
      - checkout
      - install-pnpm
      - run:
          name: install dependencies for my Project
          command: pnpm install
  lint-and-test:
    executor: node/default
    steps:
      - install-pnpm
      - attach_workspace:
          at: .
      - run:
          name: run lint
          command: pnpm run lint:ci --all
      - run:
          name: run unit test
          command: pnpm run test:unit        

workflows:
  test:
    jobs:
      - install-deps
    - lint-and-test:
          name: my-blog      